INSERT INTO `gtdsample_categories` VALUES ('1','Professional','Work related.');
INSERT INTO `gtdsample_categories` VALUES ('2','Personal','Outside of work.');
-- *******************************
INSERT INTO `gtdsample_context` VALUES ('1','Computer','Sitting at a keyboard.');
INSERT INTO `gtdsample_context` VALUES ('2','Office','At the office');
INSERT INTO `gtdsample_context` VALUES ('3','Phone','Calls');
INSERT INTO `gtdsample_context` VALUES ('4','Home','Something you can only do from home.\r\n');
-- *******************************
INSERT INTO `gtdsample_items` VALUES ('1','Set up your new gtd-php system','Getting Things Done','Mind like water.',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('3','Do a weekly review to help populate this system','Click on <a href=\'weekly.php\'>this link</a> to see the Weekly Review: you can use this as a guide to help set up the system - there\'s an accompanying <a href=\'itemReport.php?itemId=19\'>Weekly Review checklist</a> for you to tick off the tasks, each week.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('4','gtd-php user forums','the gtd-php <a href=\'http://toae.org/boards/\'>user forums</a> are the place to go to ask questions and meet others  in the gtd-php community','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('5','delete this action, which is deliberately an orphan','and can safely be deleted, by editing this item, then checking the \"delete\" box below, and then pressing the \"update\" button','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('6','Stay on top of things, and don\'t lose track of what needs doing','','Having one place where you trust yourself to list all of the things you need to do, which means you can keep your mind clear for whatever it is you\'re doing at any one moment, without being distracted by all the things you\'re not doing at that moment ',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('8','review the checklist of things to do to start','We\'ve created a <a href=\'itemReport.php?itemId=15\'>\"gtd-php startup things-to-do\" list</a> for you to start with.  Once you\'ve done these things, then you\'re ready to start adding your own actions: which means you can now make the <b>\"Do a weekly review to help populate this system\"</b> action into a <i>Next</i> Action.  To do that, in the <a href=\'itemReport.php?itemId=1\'>project</a> screen, check the \"Next Action\" box and then press the \"update\" button immediately below it.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('9','Update GTD-PHP','Whenever a new release comes out, you should upgrade your GTD-PHP application.  This is a sample of a waiting-on event.  This is something outside of your control, but you can make it the \"next action\" so that a project doesn\'t ask you for a next action.  This is helpful when your next action on a project is for someone else to contact you or send you something.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('10','Drop items into your inbox','You have an \"inbox\" for quickly adding items to you GTD-PHP system.  After you use <strong>Capture-><a href=\"item.php?type=i\">Inbox</a></strong>, you can then <a href=\"listItems.php?type=i\">view all your inbox items</a> so they may be added to <a href=\"listItems.php?type=p\">projects</a>.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('11','Read Additional References','The someday/maybe area is for projects you may not get to in the very near future, but you need a place to store the gist of the project, maybe a few notes/references, and this makes it easy to take the idea \"live\" by translating it into a project.\r\n\r\nIf you decide to take this project on, and think you\'ll be working on it in the next month or so, edit this item and <strong>un</strong>check the \"Someday\" box at the bottom.  Then it will be a normal project.\r\n\r\nYou may want to consider reading additional books about time management and prioritization, which  can help you organize your projects and priorities.  See the references for this someday/maybe item for ideas of other materials and books that you might want to read or look into.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('12','Getting Things Done','by David Allen\r\n\r\nThis application is based on his project/action management philosophies.\r\n\r\nISBN-10: 0142000280\r\nISBN-13: 978-0142000281\r\n','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('13','The 7 Habits of Highly Effective People','by Stephen R. Covey\r\n\r\nThere are many books in the genre, including Sean Covey\'s 7 Habits of Highly Effective Teens.  For the first groundbreaking book on managing yourself see:\r\n\r\nISBN-10: 0743269519\r\nISBN-13: 978-0743269513\r\n\r\nThis book influenced some of the developers of this application.  Covey doesn\'t go into project management to the level of detail of David Allen, and David Allen doesn\'t go into goal and vision management to the degree of Stephen Covey.  Since they can be viewed in a complimentary manner, one can read both and come out with a good map and a way to manage getting there on a day-to-day basis.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('14','43 Folders Website','You may want to look into the resources at <a href=\"http://www.43folders.com/\">43 Folders</a> which are usually based on David Allen\'s work. There are many resources there that are helpful for time management and project management.','',NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('15','gtd-php startup things-to-do','A list of things you should check out in the new sample data generated for you.\r\n\r\nLists are for one-time simple lists that once done you\'ll no longer need.  For reusable lists see checklists.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('16','categories','Check the <a href=\'editCat.php?field=category\'>categories</a> meet your needs',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('17','space contexts','Check the <a href=\'editCat.php?field=context\'>space contexts</a> meet your needs',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('18','time contexts','Check the <a href=\'editCat.php?field=time-context\'>time contexts</a> meet your needs',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('19','Weekly Review Checklist','Use this checklist every week to make sure that you have done everything you need to do to keep GTD-PHP up-to-date.\r\n\r\nChecklists are re-usable lists.  Use them for processes you need to repeat over and over again.  When you need to do the list over from the beginning use the clear checklist option and all the checkmarks will go away.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('20','Gather all loose papers','',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('21','Process all notes','',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('22','Check all voice mail','',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('23','Review Email Inbox','Move each item to an action, waiting, or reference folder.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('24','Review Email action box','Put next action reminder into system for each one, delete completed emails or move to waiting on or reference boxes as approriate.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('25','Review Email waiting on box','Put waiting on reminder into system for each one, delete completed emails or move to reference box as approriate.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('26','Review previous calendar','Transfer any missed actions to system',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('27','Purge agendas','',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('28','Review upcoming calendar','Capture actions about arrangements and preparations for any upcoming events',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('29','Empty your head','Put in writing any <a href=\"item.php?type=p\" target=\"_blank\">new projects</a>, <a href=\"item.php?type=a\" target=\"_blank\">actions</a>, <a href=\"item.php?type=w\" target=\"_blank\">things you are waiting for</a>, <a href=\"item.php?type=r\" target=\"_blank\">references</a>, and <a href=\"item.php?type=p&someday=true\" target=\"_blank\">someday/maybes</a> that are not yet in the system.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('30','Empty your gtd-php inbox','See your <a href=\"listItems.php?type=i\" target=\"_blank\">gtd-php inbox</a>.  Use the \'Set Type\' button to convert each one into a project, action, reference or waiting-on',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('31','Review Projects list','See <a href=\"listItems.php?type=p\" target=\"_blank\">your projects list.</a> Make sure that all projects have next actions defined.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('32','Review Actions list','See <a href=\"listItems.php?type=a\" target=\"_blank\">your actions list.</a>  Mark off any completed actions, review for reminders of further actions to capture.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('33','Review WaitingOn list','See <a href=\"listItems.php?type=w\" target=\"_blank\">your waiting on list.</a>  Mark off any items which have now happened; for each such item\'s parent project, decide what the new next action is.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('34','Review Lists','See <a href=\"listItems.php?type=L\" target=\"_blank\">your lists</a>.  Review relevant lists for actionable items or projects.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('35','Review Checklists','See <a href=\"listItems.php?type=C\" target=\"_blank\">your checklists.</a> Review relevant Checklists for actionable items or projects.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('36','Review Someday/Maybe List','See <a href=\"listItems.php?type=p&someday=true\" target=\"_blank\">your someday/maybe list.</a>  Add new fun things, move any existing items into Projects if they are ready to go.',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('37','Review support files','',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('38','Review Goals','See <a href=\"listItems.php?type=g\" target=\"_blank\">your goals.</a>  Check off goals from this week. Define goals for upcoming week',NULL,NULL,NULL);
INSERT INTO `gtdsample_items` VALUES ('39','Brainstorm','Get creative with any new <a href=\"item.php?type=p\" target=\"_blank\">projects</a> or <a href=\"item.php?type=p&someday=true\" target=\"_blank\">someday/maybes</a> that may further your values, visions, goals, or areas of responsibility.',NULL,NULL,NULL);
-- *******************************
INSERT INTO `gtdsample_itemstatus` VALUES ('1','2007-10-17','2008-11-07 09:32:14',NULL,'p','1','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('3','2007-10-17','2008-11-07 09:32:17',NULL,'a','1','n','1','1',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('4','2007-10-17','2008-11-07 09:32:17',NULL,'r','2','n','1','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('5','2007-10-17','2008-11-07 09:32:17',NULL,'a','2','n','1','1',NULL,NULL,'y');
INSERT INTO `gtdsample_itemstatus` VALUES ('6','2007-10-17','2008-11-07 09:32:14',NULL,'g','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('8','2007-10-19','2008-11-07 09:32:17',NULL,'a','1','n','1','1',NULL,NULL,'y');
INSERT INTO `gtdsample_itemstatus` VALUES ('9','2007-10-22','2008-11-07 09:32:17',NULL,'w','1','n','1','0',NULL,NULL,'y');
INSERT INTO `gtdsample_itemstatus` VALUES ('10','2007-10-22','2008-11-07 09:32:17',NULL,'i','1','n','1','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('11','2007-10-22','2008-11-07 09:32:17',NULL,'p','2','y','0','3',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('12','2007-10-22','2008-11-07 09:32:17',NULL,'r','2','n','4','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('13','2007-10-22','2008-11-07 09:32:17',NULL,'r','2','n','4','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('14','2007-10-22','2008-11-07 09:32:17',NULL,'r','2','n','1','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('15','2008-11-07','2008-11-07 09:32:14',NULL,'L','2','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('16','2008-11-07','2008-11-07 09:32:14',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('17','2008-11-07','2008-11-07 09:32:14',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('18','2008-11-07','2008-11-07 09:32:14',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('19','2008-11-07','2008-11-07 09:32:14',NULL,'C','2','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('20','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('21','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('22','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('23','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('24','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('25','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('26','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('27','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('28','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('29','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('30','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('31','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('32','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('33','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('34','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('35','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('36','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('37','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('38','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
INSERT INTO `gtdsample_itemstatus` VALUES ('39','2008-11-07','2008-11-07 09:32:15',NULL,'T','0','n','0','0',NULL,NULL,'n');
-- *******************************
INSERT INTO `gtdsample_lookup` VALUES ('1','3');
INSERT INTO `gtdsample_lookup` VALUES ('1','4');
INSERT INTO `gtdsample_lookup` VALUES ('1','8');
INSERT INTO `gtdsample_lookup` VALUES ('1','9');
INSERT INTO `gtdsample_lookup` VALUES ('11','12');
INSERT INTO `gtdsample_lookup` VALUES ('11','13');
INSERT INTO `gtdsample_lookup` VALUES ('11','14');
INSERT INTO `gtdsample_lookup` VALUES ('15','16');
INSERT INTO `gtdsample_lookup` VALUES ('15','17');
INSERT INTO `gtdsample_lookup` VALUES ('15','18');
INSERT INTO `gtdsample_lookup` VALUES ('19','20');
INSERT INTO `gtdsample_lookup` VALUES ('19','21');
INSERT INTO `gtdsample_lookup` VALUES ('19','22');
INSERT INTO `gtdsample_lookup` VALUES ('19','23');
INSERT INTO `gtdsample_lookup` VALUES ('19','24');
INSERT INTO `gtdsample_lookup` VALUES ('19','25');
INSERT INTO `gtdsample_lookup` VALUES ('19','26');
INSERT INTO `gtdsample_lookup` VALUES ('19','27');
INSERT INTO `gtdsample_lookup` VALUES ('19','28');
INSERT INTO `gtdsample_lookup` VALUES ('19','29');
INSERT INTO `gtdsample_lookup` VALUES ('19','30');
INSERT INTO `gtdsample_lookup` VALUES ('19','31');
INSERT INTO `gtdsample_lookup` VALUES ('19','32');
INSERT INTO `gtdsample_lookup` VALUES ('19','33');
INSERT INTO `gtdsample_lookup` VALUES ('19','34');
INSERT INTO `gtdsample_lookup` VALUES ('19','35');
INSERT INTO `gtdsample_lookup` VALUES ('19','36');
INSERT INTO `gtdsample_lookup` VALUES ('19','37');
INSERT INTO `gtdsample_lookup` VALUES ('19','38');
INSERT INTO `gtdsample_lookup` VALUES ('19','39');
-- *******************************
INSERT INTO `gtdsample_preferences` VALUES ('2','0','config','a:37:{s:5:\"title\";s:7:\"GTD-PHP\";s:8:\"datemask\";s:7:\"Y-m-d D\";s:5:\"theme\";s:7:\"default\";s:12:\"title_suffix\";b:0;s:10:\"trimLength\";i:72;s:18:\"trimLengthInReport\";i:0;s:14:\"firstDayOfWeek\";i:0;s:25:\"ReportMaxCompleteChildren\";i:0;s:19:\"useLiveEnhancements\";b:1;s:21:\"showRelativeDeadlines\";b:0;s:14:\"contextsummary\";b:0;s:11:\"afterCreate\";a:9:{s:1:\"i\";s:7:\"another\";s:1:\"a\";s:6:\"parent\";s:1:\"w\";s:6:\"parent\";s:1:\"r\";s:6:\"parent\";s:1:\"p\";s:4:\"list\";s:1:\"m\";s:4:\"item\";s:1:\"v\";s:4:\"item\";s:1:\"o\";s:4:\"item\";s:1:\"g\";s:4:\"list\";}s:17:\"suppressAsOrphans\";s:23:\"\'i\',\'m\',\'v\',\'o\',\'g\',\'p\'\";s:29:\"reviewProjectsWithoutOutcomes\";b:1;s:5:\"show7\";b:0;s:16:\"storeRecurrences\";b:1;s:23:\"useTypesForTimeContexts\";b:0;s:9:\"separator\";s:25:\"^&*#@#%&*%^@$^*$$&%#@#@^^\";s:14:\"forceAllFields\";b:0;s:18:\"allowChangingTypes\";b:0;s:13:\"suppressAdmin\";b:0;s:25:\"suppressCustomRecurrences\";b:1;s:7:\"charset\";s:10:\"ISO8859-15\";s:19:\"withholdVersionInfo\";b:0;s:12:\"afterCreatem\";s:4:\"item\";s:12:\"afterCreatev\";s:4:\"item\";s:12:\"afterCreateo\";s:4:\"item\";s:12:\"afterCreateg\";s:4:\"list\";s:12:\"afterCreatep\";s:4:\"list\";s:12:\"afterCreatea\";s:6:\"parent\";s:12:\"afterCreatei\";s:7:\"another\";s:12:\"afterCreates\";s:4:\"item\";s:12:\"afterCreater\";s:6:\"parent\";s:12:\"afterCreatew\";s:6:\"parent\";s:12:\"afterCreateL\";s:4:\"item\";s:12:\"afterCreateC\";s:4:\"item\";s:12:\"afterCreateT\";s:4:\"item\";}');
INSERT INTO `gtdsample_preferences` VALUES ('3','0','keys','a:13:{s:15:\"item.php?type=i\";s:1:\"i\";s:15:\"item.php?type=p\";s:1:\"p\";s:23:\"listItems.php?quickfind\";s:1:\"f\";s:20:\"listItems.php?type=a\";s:1:\"a\";s:38:\"listItems.php?type=a&amp;nextonly=true\";s:1:\"n\";s:20:\"listItems.php?type=p\";s:1:\"v\";s:33:\"listItems.php?type=p&someday=true\";s:1:\"m\";s:20:\"listItems.php?type=w\";s:1:\"w\";s:20:\"listLists.php?type=C\";s:1:\"c\";s:20:\"listLists.php?type=L\";s:1:\"l\";s:17:\"reportContext.php\";s:1:\"x\";s:9:\"index.php\";s:1:\"s\";s:10:\"weekly.php\";s:1:\"r\";}');
INSERT INTO `gtdsample_preferences` VALUES ('4','0','hierarchy','a:4:{s:5:\"names\";a:13:{s:1:\"m\";s:5:\"value\";s:1:\"v\";s:6:\"vision\";s:1:\"o\";s:4:\"role\";s:1:\"g\";s:4:\"goal\";s:1:\"p\";s:7:\"Project\";s:1:\"a\";s:6:\"Action\";s:1:\"i\";s:10:\"Inbox Item\";s:1:\"s\";s:13:\"Someday/Maybe\";s:1:\"r\";s:9:\"Reference\";s:1:\"w\";s:10:\"Waiting On\";s:1:\"L\";s:4:\"List\";s:1:\"C\";s:9:\"Checklist\";s:1:\"T\";s:9:\"List item\";}s:17:\"suppressAsOrphans\";s:8:\"imvogpLC\";s:8:\"children\";a:12:{s:1:\"m\";a:2:{i:0;s:1:\"v\";i:1;s:1:\"o\";}s:1:\"v\";a:4:{i:0;s:1:\"o\";i:1;s:1:\"g\";i:2;s:1:\"C\";i:3;s:1:\"L\";}s:1:\"o\";a:4:{i:0;s:1:\"g\";i:1;s:1:\"p\";i:2;s:1:\"C\";i:3;s:1:\"L\";}s:1:\"g\";a:3:{i:0;s:1:\"p\";i:1;s:1:\"C\";i:2;s:1:\"L\";}s:1:\"p\";a:6:{i:0;s:1:\"a\";i:1;s:1:\"w\";i:2;s:1:\"p\";i:3;s:1:\"r\";i:4;s:1:\"C\";i:5;s:1:\"L\";}s:1:\"w\";a:0:{}s:1:\"a\";a:0:{}s:1:\"r\";a:0:{}s:1:\"i\";a:0:{}s:1:\"C\";a:1:{i:0;s:1:\"T\";}s:1:\"L\";a:1:{i:0;s:1:\"T\";}s:1:\"T\";a:0:{}}s:7:\"parents\";a:12:{s:1:\"m\";a:0:{}s:1:\"v\";a:1:{i:0;s:1:\"m\";}s:1:\"o\";a:2:{i:0;s:1:\"v\";i:1;s:1:\"m\";}s:1:\"g\";a:2:{i:0;s:1:\"o\";i:1;s:1:\"v\";}s:1:\"p\";a:3:{i:0;s:1:\"g\";i:1;s:1:\"o\";i:2;s:1:\"p\";}s:1:\"w\";a:1:{i:0;s:1:\"p\";}s:1:\"a\";a:1:{i:0;s:1:\"p\";}s:1:\"r\";a:1:{i:0;s:1:\"p\";}s:1:\"i\";a:0:{}s:1:\"C\";a:4:{i:0;s:1:\"p\";i:1;s:1:\"v\";i:2;s:1:\"o\";i:3;s:1:\"g\";}s:1:\"L\";a:4:{i:0;s:1:\"p\";i:1;s:1:\"v\";i:2;s:1:\"o\";i:3;s:1:\"g\";}s:1:\"T\";a:2:{i:0;s:1:\"L\";i:1;s:1:\"C\";}}}');
INSERT INTO `gtdsample_preferences` VALUES ('5','0','debug','a:5:{s:3:\"key\";s:1:\"h\";s:4:\"wait\";b:0;s:5:\"debug\";b:0;s:6:\"freeze\";b:0;s:6:\"notice\";b:0;}');
INSERT INTO `gtdsample_preferences` VALUES ('6','0','sort','a:7:{s:17:\"categoryselectbox\";s:16:\"c.`category` ASC\";s:11:\"getchildren\";s:56:\"its.`dateCompleted` DESC, `deadline` DESC, i.`title` ASC\";s:8:\"getitems\";s:13:\"i.`title` ASC\";s:17:\"getitemsandparent\";s:105:\"DATEDIFF(CURDATE(),dateCompleted) ASC, DATEDIFF(CURDATE(),deadline) DESC, type ASC, ptitle ASC, title ASC\";s:16:\"getorphaneditems\";s:25:\"`type` ASC, i.`title` ASC\";s:21:\"spacecontextselectbox\";s:13:\"cn.`name` ASC\";s:20:\"timecontextselectbox\";s:19:\"ti.`timeframe` DESC\";}');
INSERT INTO `gtdsample_preferences` VALUES ('7','0','addons','a:0:{}');
-- *******************************
INSERT INTO `gtdsample_timeitems` VALUES ('1','Short','< 10 Minutes','a');
INSERT INTO `gtdsample_timeitems` VALUES ('2','Medium','10-30 Minutes','a');
INSERT INTO `gtdsample_timeitems` VALUES ('3','Long','> 30 Minutes','a');
-- *******************************
